### ISSUE TITLE
64位 ubuntu20.04 install.sh脚本异常

### ISSUE THREAD

**Issue by cd871127** [qinming99/dst-admin#2]
执行到第5行,提示包不存在  sudo apt-get install -y libcurl4-gnutls-dev:i386

需要
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libcurl4-gnutls-dev:i386

**Comment by qinming99** [comment]
HI :


&nbsp;我尝试在Ubuntu20.04上执行了一下，还是报错的，install.sh脚本虽然报错了，但是实际上还是可以使用的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinming99/dst-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午4:59
收件人:&nbsp;"qinming99/dst-admin"<dst-admin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qinming99/dst-admin] 64位 ubuntu20.04 install.sh脚本异常 (#2)





 
执行到第5行,提示包不存在  sudo apt-get install -y libcurl4-gnutls-dev:i386
 
需要
 sudo dpkg --add-architecture i386
 sudo apt-get update
 sudo apt-get install libcurl4-gnutls-dev:i386
