### ISSUE TITLE
严重安全问题

### ISSUE THREAD

**Issue by Xc1Ym** [qinming99/dst-admin#27]
该软件系统存在任意文件下载漏洞，使用默认口令登录账号后，可以通过`/backup/download?fileName=../../../../../../../../../../../../../../etc/passwd`地址直接下载Linux操作系统的敏感文件，目前全球718台主机使用该软件系统，其中已发现超过数十台主机存在默认口令，通过该口令可以获取`passwd`以及`shadow`文件，通过上述文件可破解操作系统登录口令
![图片2](https://user-images.githubusercontent.com/29765332/142873775-28a4c68b-e988-48f8-a165-4ca7a831b6e7.png)

**Comment by qinming99** [comment]
v1.3.1已修复，建议升级到最新版本
