### ISSUE TITLE
内存占用高

### ISSUE THREAD

**Issue by waingt** [qinming99/dst-admin#31]
在Ubuntu 20.04 LTS上使用docker拉取运行了当前最新版V1.3.1
运行饥荒时内存占用达到1672MB/2GB 92%（裸机没有其他进程）
top查看java进程使用了230MB内存, 而且在不断增加
请问这个内存占用正常吗😢

**Comment by qinming99** [comment]
正常，docker本身要使用内存，java程序也需要使用内存，还有其他的服务都需要内存，2GB内存使用docker完全不够的

**Comment by waingt** [comment]
感谢解答
