### ISSUE TITLE
求助：服务器启动后，进不了WEB管理页面

### ISSUE THREAD

**Issue by uncleEli** [qinming99/dst-admin#36]
我没有用docker那套去部署
用的./dstStart.sh
看了一下是正常运行中
但是为啥8080端口看不到web管理页面啊？
![image](https://user-images.githubusercontent.com/94106788/149486682-4f5ade79-a458-47ef-b2f5-5178daec32d3.png)

**Comment by CZ8966** [comment]
看看端口开没开
systemctl start firewalld.service
firewall-cmd --state
firewall-cmd --zone=public --list-all
firewall-cmd --add-port=1194/tcp --permanent
firewall-cmd --add-port=1194/udp --permanent
firewall-cmd --reload

**Comment by uncleEli** [comment]
解决了，请删除这个issue谢谢
