### ISSUE TITLE
设置mod不生效问题

### ISSUE THREAD

**Issue by xjblszyy** [qinming99/dst-admin#57]
我设置了海难联机mod，但是不生效，我从我本地mod copy的一份过来，而且只开了这两个mod，在本地的就能正常，但是在服务器就不行，求助下大佬是什么问题
`return {
  ["workshop-1378549454"]={
    configuration_options={
      ["MemSpikeFix:"]=false,
      MemSpikeFixmaster_override=true,
      ["MemSpikeFixworkshop-1216718131"]="default",
      ["MemSpikeFixworkshop-1467214795"]="default",
      ["MemSpikeFixworkshop-1651623054"]="default",
      ["MemSpikeFixworkshop-345692228"]="default",
      ["MemSpikeFixworkshop-347079953"]="default",
      ["MemSpikeFixworkshop-351325790"]="default",
      ["MemSpikeFixworkshop-356930882"]="default",
      ["MemSpikeFixworkshop-362175979"]="default",
      ["MemSpikeFixworkshop-363112314"]="default",
      ["MemSpikeFixworkshop-365119238"]="default",
      ["MemSpikeFixworkshop-367546858"]="default",
      ["MemSpikeFixworkshop-375850593"]="default",
      ["MemSpikeFixworkshop-375859599"]="default",
      ["MemSpikeFixworkshop-376333686"]="default",
      ["MemSpikeFixworkshop-378160973"]="default",
      ["MemSpikeFixworkshop-382177939"]="default",
      ["MemSpikeFixworkshop-463292274"]="default",
      ["MemSpikeFixworkshop-572538624"]="default",
      ["MemSpikeFixworkshop-609051112"]="default",
      craftinghighlight=false 
    },
    enabled=true 
  },
  ["workshop-1467214795"]={
    configuration_options={
      ["Cut Content Restoration"]=false,
      aquaticplacedstwater=false,
      bioluminescenceicon=true,
      caveid=false,
      devmode=false,
      droplootground=true,
      dynamicmusic=true,
      fixnoplayerboats=true,
      forestid=false,
      krakenbuff=true,
      leif_jungle=false,
      limestonerepair=true,
      locale=false,
      newloot="all",
      newplayerboats=true,
      octopuskingtweak=true,
      octopustrade=true,
      oldwarly=false,
      pondfishable=true,
      quickseaworthy=false,
      sealabtweak=true,
      shipwreckedid=false,
      slotmachineloot=true,
      tarlampbuff=true,
      tarsuitbuff=true,
      tigerbuff=false,
      tuningmodifiers=true,
      volcanoid=false,
      windgustable="all",
      windstaffbuff=2,
      ["人物修改"]=false,
      ["多(三层以上)世界选项,不要乱改"]=false,
      ["杂项"]=false,
      ["游戏功能"]=false,
      ["物品和建筑"]=false,
      ["生物改变"]=false 
    },
    enabled=true 
  } 
}`

**Comment by xjblszyy** [comment]
而且我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版本，不是海难版本

**Comment by zyd100** [comment]
> 而且我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版本，不是海难版本

最好是在本地生成了一份存档后上传到服务器上，我也遇到同样的问题，

**Comment by xjblszyy** [comment]
> > 而我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版，不是海难版
> 
> 最好的是在本地生成了一份存档后上传到服务器上，我也遇到了同样的问题，

这就是本地生成的，传上去的

**Comment by zyd100** [comment]
> > > 而我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版，不是海难版
> > 
> > 
> > 最好的是在本地生成了一份存档后上传到服务器上，我也遇到了同样的问题，
> 
> 这就是本地生成的，传上去的

你本地生成是只传了mod设置吗，是需要本地创建好海难房间后把整份存档传上去

**Comment by xjblszyy** [comment]
> > > > 而我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版，不是海难版
> > > 
> > > 
> > > 最好的是在本地生成了一份存档后上传到服务器上，我也遇到了同样的问题，
> > 
> > 
> > 这就是本地生成的，传上去的
> 
> 你本地生成是只传了mod设置吗，是需要本地创建好海难房间后把整份存档传上去

原来是这样啊，感谢大佬，我试试

**Comment by zyd100** [comment]
> > > > > 而我在服务器游戏mod中能看到这两个mod已经安装成功了，但是进游戏还是普通版，不是海难版
> > > > 
> > > > 
> > > > 最好的是在本地生成了一份存档后上传到服务器上，我也遇到了同样的问题，
> > > 
> > > 
> > > 这就是本地生成的，传上去的
> > 
> > 
> > 你本地生成是只传了mod设置吗，是需要本地创建好海难房间后把整份存档传上去
> 
> 原来是这样啊，感谢大佬，我试试

传上去后记得房间设置的地上世界和洞穴世界配置也要设置好，防止出现啥奇怪的bug
