### ISSUE TITLE
将主世界和洞穴放在不同服务器时会出现bug

### ISSUE THREAD

**Issue by Vandalizegod** [qinming99/dst-admin#6]
因为云主机内存不足，所以我将地上世界和洞穴分别放在两台服务器上面，并且在两台服务器都使用了dst-admin管理，一台只启动地面，一台只启动洞穴。
正常玩是没问题的，但有时候连接时却会发生无法连接服务器。进入dst-admin的网页后，发现其中一台服务器上地面和洞穴都全部自动启动了（可能是地面那台服务器，可能是洞穴那台服务器，偶尔也可能都启动了）。

**Comment by qinming99** [comment]
升级到最新版本，在自动更新时可以设置更新游戏时启动粒度
