### ISSUE TITLE
需求-增加版本检测与自动更新的频率

### ISSUE THREAD

**Issue by sukeme** [qinming99/dst-admin#9]
新版本发布后，实验室内显示最新版本号要挺久才会同步到最新。
最新版本号更新后，服务器又会过一段时间才会自动更新，间隔时间有点长，今天经过了八九个小时后发现还未自动更新。
猜测是版本检测与自动更新设定的启动间隔太久？是否可以提高检测频率，优化体验，减少大厅搜索不到的时间。

**Comment by qinming99** [comment]
智能更新已修复
